insert into slotmachine.airline values('Aer Lingus','EIN','Ireland');
insert into slotmachine.airline values('Olympic Airlines','OAL','Greece');
insert into slotmachine.airline values('Mistral Air','MSA','Italy');
insert into slotmachine.airline values('Ryanair','RYR','Ireland');
insert into slotmachine.airline values('Widerøe','WIF','Norway');
insert into slotmachine.airline values('Flybe','BEE','United Kingdom');
insert into slotmachine.airline values('TAP Portugal','TAP','Portugal');
insert into slotmachine.airline values('Lufthansa','DLH','Germany');
insert into slotmachine.airline values('Aeroflot Russian Airlines','AFL','Russia');
insert into slotmachine.airline values('Air France','AFR','France');
insert into slotmachine.airline values('Air Europa','AEA','Spain');
insert into slotmachine.airline values('easyJet','EZY','United Kingdom');
insert into slotmachine.airline values('Turkish Airlines','THY','Turkey');
insert into slotmachine.airline values('BA CityFlyer','CFE','United Kingdom');
insert into slotmachine.airline values('Eurowings','EWG','Germany');
insert into slotmachine.airline values('British Airways','BAW','United Kingdom');
insert into slotmachine.airline values('Air Satellite','ASJ','Canada');
insert into slotmachine.airline values('KLM Royal Dutch Airlines','KLM','Netherlands');
insert into slotmachine.airline values('Israir','ISR','Israel');
insert into slotmachine.airline values('Jetairfly','JAF','Belgium');
insert into slotmachine.airline values('Egyptair','MSR','Egypt');
insert into slotmachine.airline values('Air Nostrum','ANE','Spain');
insert into slotmachine.airline values('Nippon Cargo Airlines','NCA','Japan');
insert into slotmachine.airline values('Cygnus Air','RGN','Spain');
insert into slotmachine.airline values('Finnair','FIN','Finland');
insert into slotmachine.airline values('Corendon Airlines','CAI','Turkey');
insert into slotmachine.airline values('Tuninter','TUI','Tunisia');
insert into slotmachine.airline values('UTair Aviation','UTA','Russia');
insert into slotmachine.airline values('British Airways Shuttle','SHT','United Kingdom');
insert into slotmachine.airline values('Air Baltic','BTI','Latvia');
insert into slotmachine.airline values('Vueling Airlines','VLG','Spain');
insert into slotmachine.airline values('Wizz Air','WZZ','Hungary');
insert into slotmachine.airline values('Scandinavian Airlines System','SAS','Sweden');
insert into slotmachine.airline values('Abelag Aviation','AAB','Belgium');
insert into slotmachine.airline values('Emirates','UAE','United Arab Emirates');
insert into slotmachine.airline values('Iberia Express','IBS','Spain');
insert into slotmachine.airline values('Iberia Airlines','IBE','Spain');
insert into slotmachine.airline values('Austrian Airlines','AUA','Austria');
insert into slotmachine.airline values('Aigle Azur','AAF','France');
insert into slotmachine.airline values('Bulgaria Air','LZB','Bulgaria');
insert into slotmachine.airline values('Air Moldova','MLD','Moldova');
insert into slotmachine.airline values('Meridiana','ISS','Italy');
insert into slotmachine.airline values('Georgian Airways','TGZ','Georgia');
insert into slotmachine.airline values('Air Algerie','DAH','Algeria');
insert into slotmachine.airline values('Alitalia','AZA','Italy');
insert into slotmachine.airline values('Jet2.com','EXS','United Kingdom');
insert into slotmachine.airline values('Pobeda','PBD','Russia');
insert into slotmachine.airline values('Norwegian Air Shuttle','NAX','Norway');
insert into slotmachine.airline values('Qatar Airways','QTR','Qatar');
insert into slotmachine.airline values('Etihad Airways','ETD','United Arab Emirates');
insert into slotmachine.airline values('China Eastern Airlines','CES','China');
insert into slotmachine.airline values('Onur Air','OHY','Turkey');
insert into slotmachine.airline values('Croatia Airlines','CTN','Croatia');
insert into slotmachine.airline values('Swiss International Air Lines','SWR','Switzerland');
insert into slotmachine.airline values('Royal Air Maroc','RAM','Morocco');
insert into slotmachine.airline values('Blue Panorama Airlines','BPA','Italy');
insert into slotmachine.airline values('Ukraine International Airlines','AUI','Ukraine');
insert into slotmachine.airline values('VOLOTEA Airways','VOE','Spain');
insert into slotmachine.airline values('Europe Airpost','FPO','France');
insert into slotmachine.airline values('Edelweiss Air','EDW','Switzerland');
insert into slotmachine.airline values('United Airlines','UAL','United States');
insert into slotmachine.airline values('Travel Service','TVS','Czech Republic');
insert into slotmachine.airline values('FAI Airservice','IFA','Germany');
insert into slotmachine.airline values('Air Dolomiti','DLA','Italy');
insert into slotmachine.airline values('Air Canada','ACA','Canada');
insert into slotmachine.airline values('LOT Polish Airlines','LOT','Poland');
insert into slotmachine.airline values('Saudi Arabian Airlines','SVA','Saudi Arabia');
insert into slotmachine.airline values('Belavia Belarusian Airlines','BRU','Belarus');
insert into slotmachine.airline values('Aegean Airlines','AEE','Greece');
insert into slotmachine.airline values('Tarom','ROT','Romania');
insert into slotmachine.airline values('Air Mobility Command','RCH','United States');
insert into slotmachine.airline values('Middle East Airlines','MEA','Lebanon');
insert into slotmachine.airline values('TAMPA','TPA','Colombia');
insert into slotmachine.airline values('Iran Air','IRA','Iran');
insert into slotmachine.airline values('Air West','AWT','Canada');
insert into slotmachine.airline values('Pegasus Airlines','PGT','Turkey');
insert into slotmachine.airline values('Thomsonfly','TOM','United Kingdom');
insert into slotmachine.airline values('Springdale Air Service','SPG','United States');
insert into slotmachine.airline values('Wind Rose Aviation','WRC','Ukraine');
insert into slotmachine.airline values('Max Avia','MAI','Kyrgyzstan');
insert into slotmachine.airline values('Azerbaijan Airlines','AHY','Azerbaijan');
insert into slotmachine.airline values('Southern Air','SOO','United States');
insert into slotmachine.airline values('Delta Air Lines','DAL','United States');
insert into slotmachine.airline values('Federal Express','FDX','United States');
insert into slotmachine.airline values('LAN Peru','LPE','Peru');
insert into slotmachine.airline values('Atlasjet','KKK','Turkey');
insert into slotmachine.airline values('Mediterranean Air Freight','MDF','Greece');
insert into slotmachine.airline values('Air India Limited','AIC','India');
insert into slotmachine.airline values('WestJet','WJA','Canada');
insert into slotmachine.airline values('Transavia Holland','TRA','Netherlands');
insert into slotmachine.airline values('Four Island Air','FIA','Antigua and Barbuda');
insert into slotmachine.airline values('Fly Dubai','FDB','United Arab Emirates');
insert into slotmachine.airline values('Aeronautica Militare','IAM','Italy');
insert into slotmachine.airline values('Neos','NOS','Italy');
insert into slotmachine.airline values('American Airlines','AAL','United States');
insert into slotmachine.airline values('IJM International Jet Management','IJM','Austria');
insert into slotmachine.airline values('SunExpress','SXS','Turkey');
insert into slotmachine.airline values('Malta Air Charter','MAC','Malta');
insert into slotmachine.airline values('Aurigny Air Services','AUR','United Kingdom');
insert into slotmachine.airline values('Rossiya-Russian Airlines','SDM','Russia');
insert into slotmachine.airline values('Air China','CCA','China');
insert into slotmachine.airline values('Czech Airlines','CSA','Czech Republic');
insert into slotmachine.airline values('Swiftair','SWT','Spain');
insert into slotmachine.airline values('Aerolineas Ejecutivas Tarascas','RSC','Mexico');
insert into slotmachine.airline values('Chalair Aviation','CLG','France');
insert into slotmachine.airline values('TAM Brazilian Airlines','TAM','Brazil');
insert into slotmachine.airline values('Korean Air','KAL','Republic of Korea');
insert into slotmachine.airline values('Thomas Cook Airlines','TCX','United Kingdom');
insert into slotmachine.airline values('Air Arabia Egypt','RBG','Egypt');
insert into slotmachine.airline values('AeroMéxico','AMX','Mexico');
insert into slotmachine.airline values('Transaviabaltika','KTB','Lithuania');
insert into slotmachine.airline values('Jet Airways','JAI','India');
insert into slotmachine.airline values('Katekavia','KTK','Russia');
insert into slotmachine.airline values('Transavia France','TVF','France');
insert into slotmachine.airline values('Ural Airlines','SVR','Russia');
insert into slotmachine.airline values('Luxair','LGL','Luxembourg');
insert into slotmachine.airline values('El Al Israel Airlines','ELY','Israel');
insert into slotmachine.airline values('Sky Express','SEH','Greece');
insert into slotmachine.airline values('FlyEgypt','FEG','Egypt');
insert into slotmachine.airline values('Thai Airways International','THA','Thailand');
insert into slotmachine.airline values('Airbus Transport International','BGA','France');
insert into slotmachine.airline values('All Nippon Airways','ANA','Japan');
insert into slotmachine.airline values('Air Arabia','ABY','United Arab Emirates');
insert into slotmachine.airline values('Atlantic Airlines','NPT','United Kingdom');
insert into slotmachine.airline values('Logan Air','LOG','United Kingdom');
insert into slotmachine.airline values('Silesia Air','SUA','Czech Republic');
insert into slotmachine.airline values('United Parcel Service','UPS','United States');
insert into slotmachine.airline values('AirBridge Cargo','ABW','Russia');
insert into slotmachine.airline values('Goldeck-Flug','GDK','Austria');
insert into slotmachine.airline values('Serair Transworld Press','SEV','Spain');
insert into slotmachine.airline values('Air Astana','KZR','Kazakhstan');
insert into slotmachine.airline values('Lufthansa Cargo','GEC','Germany');
insert into slotmachine.airline values('Canaryfly','CNF','Spain');
insert into slotmachine.airline values('Dubai Airwing','DUB','United Arab Emirates');
insert into slotmachine.airline values('Binter Canarias','IBB','Spain');
insert into slotmachine.airline values('Jettime','JTG','Denmark');
insert into slotmachine.airline values('Mytravel Airways','VKG','Denmark');
insert into slotmachine.airline values('Executive Jet Management','EJM','United States');
insert into slotmachine.airline values('Air China Cargo','CAO','China');
insert into slotmachine.airline values('Condor Flugdienst','CFG','Germany');
insert into slotmachine.airline values('Sakaviaservice','AZG','Georgia');
insert into slotmachine.airline values('Air Southwest','WOW','United Kingdom');
insert into slotmachine.airline values('Sky Wings Airlines','GSW','Greece');
insert into slotmachine.airline values('S7 Airlines','SBI','Russia');
insert into slotmachine.airline values('Singapore Airlines','SIA','Singapore');
insert into slotmachine.airline values('Bristow Helicopters','BHL','United Kingdom');
insert into slotmachine.airline values('Trans-Ulgii','UTN','Mongolia');
insert into slotmachine.airline values('Buffalo Express Airlines','BRX','United States');
insert into slotmachine.airline values('Tunisair','TAR','Tunisia');
insert into slotmachine.airline values('Royal Jordanian','RJA','Jordan');
insert into slotmachine.airline values('DAT Danish Air Transport','DTR','Denmark');
insert into slotmachine.airline values('Arkefly','TFL','Netherlands');
insert into slotmachine.airline values('Silk Way Airlines','AZQ','Azerbaijan');
insert into slotmachine.airline values('Aero Continente Dominicana','CND','Dominican Republic');
insert into slotmachine.airline values('European Air Transport','BCS','Belgium');
insert into slotmachine.airline values('Gestair','GES','Spain');
insert into slotmachine.airline values('SATA International','RZO','Portugal');
insert into slotmachine.airline values('Norwegian Air International (D8)','IBK','Norway');
insert into slotmachine.airline values('Tiphook PLC','BOX','United Kingdom');
insert into slotmachine.airline values('Nouvel Air Tunisie','LBT','Tunisia');
insert into slotmachine.airline values('Uzbekistan Airways','UZB','Uzbekistan');
insert into slotmachine.airline values('Arkia Israel Airlines','AIZ','Israel');
insert into slotmachine.airline values('Twin Jet','TJT','France');
insert into slotmachine.airline values('Ethiopian Airlines','ETH','Ethiopia');
insert into slotmachine.airline values('Cargolux','CLX','Luxembourg');
insert into slotmachine.airline values('Hainan Airlines','CHH','China');
insert into slotmachine.airline values('Atlas Air','GTI','United States');
insert into slotmachine.airline values('Iraqi Airways','IAW','Iraq');
insert into slotmachine.airline values('Aeropac','STK','United States');
insert into slotmachine.airline values('CAL Cargo Air Lines','ICL','Israel');
insert into slotmachine.airline values('Japan Airlines','JAL','Japan');
insert into slotmachine.airline values('Air Cairo','MSC','Egypt');
insert into slotmachine.airline values('DHL Air','DHK','United Kingdom');
insert into slotmachine.airline values('Azzurra Air','AZI','Italy');
insert into slotmachine.airline values('Globus','GLP','Russia');
insert into slotmachine.airline values('Vistajet','VJT','Canada');
insert into slotmachine.airline values('EFD Eisele Flugdienst','EFD','Germany');
insert into slotmachine.airline values('Nas Air','KNE','Saudi Arabia');
insert into slotmachine.airline values('Air Malta','AMC','Malta');
insert into slotmachine.airline values('TNT Airways','TAY','Belgium');
insert into slotmachine.airline values('Air Alsie','MMD','Denmark');
insert into slotmachine.airline values('Atlantic Richfield Company','NRS','United States');
insert into slotmachine.airline values('Global Jet Luxembourg','SVW','Luxembourg');
insert into slotmachine.airline values('Gulf Air','GFA','Oman');
insert into slotmachine.airline values('Virgin Atlantic Airways','VIR','United Kingdom');
insert into slotmachine.airline values('Jetstream Air','JSH','Hungary');
insert into slotmachine.airline values('SATA Air Acores','SAT','Portugal');
insert into slotmachine.airline values('Asiana Airlines','AAR','Republic of Korea');
insert into slotmachine.airline values('Spurling Aviation','ASL','United States');
insert into slotmachine.airline values('Avianca - Aerovias Nacionales de Colombia','AVA','AVIANCA');
insert into slotmachine.airline values('Motor Sich','MSI','Ukraine');
insert into slotmachine.airline values('Xclusive Jet Charter Limited','XJC','United Kingdom');
insert into slotmachine.airline values('Imperial Airways','PNX','United States');
insert into slotmachine.airline values('Elieuro','ELB','Italy');
insert into slotmachine.airline values('China Cargo Airlines','CKK','China');
insert into slotmachine.airline values('Astral Aviation','ACP','Kenya');
insert into slotmachine.airline values('Adria Airways','ADR','Slovenia');
insert into slotmachine.airline values('Yangtze River Express','YZR','China');
insert into slotmachine.airline values('Philippine Airlines','PAL','Philippines');
insert into slotmachine.airline values('Libyan Arab Airlines','LAA','Libya');
insert into slotmachine.airline values('SriLankan Airlines','ALK','Sri Lanka');
insert into slotmachine.airline values('Time Air','TIE','Czech Republic');
insert into slotmachine.airline values('Aeromedicare Ltd.','AMQ','United Kingdom');
insert into slotmachine.airline values('DAT Enterprise Limited','ENT','United Kingdom');
insert into slotmachine.airline values('Gama Aviation','GMA','United Kingdom');
insert into slotmachine.airline values('Cathay Pacific','CPA','Hong Kong SAR of China');
insert into slotmachine.airline values('Capital Trading Aviation','EGL','United Kingdom');
insert into slotmachine.airline values('Corsairfly','CRL','France');
insert into slotmachine.airline values('China Southern Airlines','CSN','China');
insert into slotmachine.airline values('Air Hamburg (AHO)','AHO','Germany');
insert into slotmachine.airline values('AlbaStar','LAV','Spain');
insert into slotmachine.airline values('Denver Jet','DJT','United States');
insert into slotmachine.airline values('Air Caraïbes','FWI','France');
insert into slotmachine.airline values('Shanxi Airlines','CXI','China');
insert into slotmachine.airline values('Helvetic Airways','OAW','Switzerland');
insert into slotmachine.airline values('Kenya Airways','KQA','Kenya');
insert into slotmachine.airline values('Commandement Du Transport Aerien Militaire Francais','CTM','France');
insert into slotmachine.airline values('Gestion Aerea Ajecutiva','GJT','Spain');
insert into slotmachine.airline values('Corse-Mediterranee','CCM','France');
insert into slotmachine.airline values('Triple Alpha','CLU','Germany');
insert into slotmachine.airline values('MNG Airlines','MNB','Turkey');
insert into slotmachine.airline values('Mahan Air','IRM','Iran');
insert into slotmachine.airline values('Free Bird Airlines','FHY','Turkey');
insert into slotmachine.airline values('Oman Air','OMA','Oman');
insert into slotmachine.airline values('Van Air Europe','VAA','Czech Republic');
insert into slotmachine.airline values('BH Air','BGH','Bulgaria');
insert into slotmachine.airline values('Pegasus Aviation','PEV','Greece');
insert into slotmachine.airline values('Nesma Airlines','NMA','Egypt');
insert into slotmachine.airline values('TACV','TCV','Portugal');
insert into slotmachine.airline values('Aerocentral','ATL','Mexico');
insert into slotmachine.airline values('Jet Service','JDI','Poland');
insert into slotmachine.airline values('Global Jet Austria','GLJ','Austria');
insert into slotmachine.airline values('Lufttransport','LTR','Norway');
insert into slotmachine.airline values('Force Aerienne Francaise','FAF','France');
insert into slotmachine.airline values('Jota Aviation','ENZ','United Kingdom');
insert into slotmachine.airline values('Montenegro Airlines','MGX','Montenegro');
insert into slotmachine.airline values('South African Airways','SAA','South Africa');
insert into slotmachine.airline values('Rwandair Express','RWD','Rwanda');
insert into slotmachine.airline values('OpenSkies','BOS','United Kingdom');
insert into slotmachine.airline values('Malmo Aviation','SCW','Sweden');
insert into slotmachine.airline values('Privilege Style L','PVG','Spain');
insert into slotmachine.airline values('AtlasGlobal Ukraine','UJX','Ukraine');
insert into slotmachine.airline values('Wind Jet','JET','Italy');
insert into slotmachine.airline values('Aerotal Aerolineas Territoriales de Colombia Ltda','ART','Colombia');
insert into slotmachine.airline values('ABC Bedarsflug','FTY','Austria');
insert into slotmachine.airline values('Spanish Air Force','AME','Spain');
insert into slotmachine.airline values('Nord-Flyg','NEF','Sweden');
insert into slotmachine.airline values('Air Contractors','ABR','Ireland');
insert into slotmachine.airline values('Garuda Indonesia','GIA','Indonesia');
insert into slotmachine.airline values('TUIfly Nordic','BLX','Sweden');
insert into slotmachine.airline values('Aviation Legere De LArmee De Terre','FMY','France');
insert into slotmachine.airline values('Titan Airways','AWC','United Kingdom');
insert into slotmachine.airline values('NordWind Airlines','NWS','Russia');
insert into slotmachine.airline values('Kuwait Airways','KAC','Kuwait');
insert into slotmachine.airline values('Pakistan International Airlines','PIA','Pakistan');
insert into slotmachine.airline values('Edinburgh Air Charter','EDC','United Kingdom');
insert into slotmachine.airline values('Air Jetsul','AJU','Portugal');
insert into slotmachine.airline values('Icelandair','ICE','Iceland');
insert into slotmachine.airline values('Arcus-Air Logistic','AZE','Germany');
insert into slotmachine.airline values('Star Air','STQ','Indonesia');
insert into slotmachine.airline values('Aba Air','ABP','Czech Republic');
insert into slotmachine.airline values('Aeropuelche','PUE','Chile');
insert into slotmachine.airline values('Private Wings Flugcharter','PWF','Germany');
insert into slotmachine.airline values('Tyrol Air Ambulance','TYW','Austria');
insert into slotmachine.airline values('ScotAirways','SAY','United Kingdom');
insert into slotmachine.airline values('Vietnam Airlines','HVN','Vietnam');
insert into slotmachine.airline values('Aerolineas Argentinas','ARG','Argentina');
insert into slotmachine.airline values('Qantas','QFA','Australia');
insert into slotmachine.airline values('China Airlines','CAL','Taiwan');
insert into slotmachine.airline values('EVA Air','EVA','Taiwan');
insert into slotmachine.airline values('Aviaexpress','AEH','Hungary');
insert into slotmachine.airline values('Martinair','MPH','Netherlands');
insert into slotmachine.airline values('Fab Air','FBA','Kyrgyzstan');
insert into slotmachine.airline values('Briansk State Air Enterprise','BRK','Russia');
insert into slotmachine.airline values('Pan Europeenne Air Service','PEA','France');
insert into slotmachine.airline values('Aerotrans ','ATG','Kazakhstan');
insert into slotmachine.airline values('AlMasria Universal Airlines','LMU','Egypt');
insert into slotmachine.airline values('Air Evex','EVE','Germany');
insert into slotmachine.airline values('London Executive Aviation','LNX','United Kingdom');
insert into slotmachine.airline values('Azul','AZU','Brazil');
insert into slotmachine.airline values('Toyota Canada','TOY','Canada');
insert into slotmachine.airline values('Flying Service','FYG','Belgium');
insert into slotmachine.airline values('LAN Cargo','LCO','Chile');
insert into slotmachine.airline values('Blue Islands','BCI','United Kingdom');
insert into slotmachine.airline values('Afriqiyah Airways','AAW','Libya');
insert into slotmachine.airline values('Axis Airways','AXY','France');
insert into slotmachine.airline values('Syrian Arab Airlines','SYR','Syrian Arab Republic');
insert into slotmachine.airline values('West Air Sweden','SWN','Sweden');
insert into slotmachine.airline values('Red Wings','RWZ','Russia');
insert into slotmachine.airline values('BRAZIL AIR','BZE','Brazil');
insert into slotmachine.airline values('Bristol Flying Centre','CLF','United Kingdom');
insert into slotmachine.airline values('Jet Executive International Charter','JEI','Germany');
insert into slotmachine.airline values('Turkmenistan Airlines','TUA','Turkmenistan');
insert into slotmachine.airline values('Air Atlanta Icelandic','ABD','Iceland');
insert into slotmachine.airline values('Ukraine Air Alliance','UKL','Ukraine');
insert into slotmachine.airline values('Atlantic Airways','FLI','Faroe Islands');
insert into slotmachine.airline values('Turkuaz Airlines','TRK','Turkey');
insert into slotmachine.airline values('El-Buraq Air Transport','BRQ','Libya');
insert into slotmachine.airline values('Apex Air Cargo','APX','United States');
insert into slotmachine.airline values('Jet Aviation','PJS','Switzerland');
insert into slotmachine.airline values('Luxaviation','LXA','Luxembourg');
insert into slotmachine.airline values('Masterjet','LMJ','Portugal');
insert into slotmachine.airline values('Airwing','NWG','Norway');
insert into slotmachine.airline values('BASE Regional Airlines','BRO','Netherlands');
insert into slotmachine.airline values('Sun Air of Scandinavia','SUS','Denmark');
insert into slotmachine.airline values('National Air Cargo','NCR','United States');
insert into slotmachine.airline values('Royal Netherlands Air Force','NAF','Netherlands');
insert into slotmachine.airline values('Boliviana de Aviacion (OB)','BOV','Bolivia');
insert into slotmachine.airline values('Wings of Lebanon Aviation','WLB','Lebanon');
insert into slotmachine.airline values('Bulgarian Air Charter','BUC','Bulgaria');
insert into slotmachine.airline values('Air New Zealand','ANZ','New Zealand');
insert into slotmachine.airline values('Royal Brunei Airlines','RBA','Brunei');
insert into slotmachine.airline values('CHC Helikopter Service','HKS','Norway');
insert into slotmachine.airline values('Malaysia Airlines','MAS','Malaysia');
insert into slotmachine.airline values('Air Austral','REU','France');
insert into slotmachine.airline values('Cyprus Airways','CYP','Cyprus');
insert into slotmachine.airline values('Kalitta Air','CKS','United States');
insert into slotmachine.airline values('Air Transat','TSC','Canada');
insert into slotmachine.airline values('Amapola Flyg AB','APF','Sweden');
insert into slotmachine.airline values('MIAT Mongolian Airlines','MGL','Mongolia');
insert into slotmachine.airline values('Rubystar','RSB','Belarus');
insert into slotmachine.airline values('Flexflight','FXT','Denmark');
insert into slotmachine.airline values('Omni Air International','OAE','United States');
insert into slotmachine.airline values('Skytaxi','IGA','Poland');
insert into slotmachine.airline values('Eurocypria Airlines','ECA','Cyprus');
insert into slotmachine.airline values('Novair','NVR','Sweden');
insert into slotmachine.airline values('Sirio','SIO','Italy');
insert into slotmachine.airline values('Aerodienst GmbH','ADN','Germany');
insert into slotmachine.airline values('Carpatair','KRP','Romania');
insert into slotmachine.airline values('Eastern Airways','EZE','United Kingdom');
insert into slotmachine.airline values('Swedish Armed Forces','SVF','Sweden');
insert into slotmachine.airline values('My Way Airlines','MYW','Italy');
insert into slotmachine.airline values('Xiamen Airlines','CXA','China');
insert into slotmachine.airline values('Air Mauritius','MAU','Mauritius');
insert into slotmachine.airline values('LatCharter','LTC','Latvia');
insert into slotmachine.airline values('Lion Air Services','WGT','United Kingdom');
insert into slotmachine.airline values('Woodgate Executive Air Charter','CWY','United Kingdom');
insert into slotmachine.airline values('Japan Air System','JAS','Japan');
insert into slotmachine.airline values('Eastern Atlantic Virtual Airlines','EAV','United States');
insert into slotmachine.airline values('City ','SDR','Sweden');
insert into slotmachine.airline values('Company ','CYF','Denmark');
insert into slotmachine.airline values('Sundt Air','MDT','Norway');
insert into slotmachine.airline values('Air Glaciers','AGV','Switzerland');
insert into slotmachine.airline values('Windrose Air','QGA','Germany');
insert into slotmachine.airline values('Blue Jet','BLJ','Spain');
insert into slotmachine.airline values('LAN Airlines','LAN','Chile');
insert into slotmachine.airline values('Surinam Airways','SLM','Suriname');
insert into slotmachine.airline values('Tassili Airlines','DTH','Algeria');
insert into slotmachine.airline values('Germanwings','GWI','Germany');
insert into slotmachine.airline values('Stuttgarter Flugdienst','FFD','Germany');
insert into slotmachine.airline values('Aliparma','PAJ','Italy');
insert into slotmachine.airline values('Air Pullmantur','PLM','Spain');
insert into slotmachine.airline values('Abu Dhabi Amiri ','AUH','United Arab Emirates');
insert into slotmachine.airline values('Portuguese Air Force','AFP','Portugal');
insert into slotmachine.airline values('Hahn Air','HHN','Germany');
insert into slotmachine.airline values('Delta Air Elite','ELJ','United States');
insert into slotmachine.airline values('Air VIP','RVP','Portugal');
insert into slotmachine.airline values('HT Helikoptertransport','KTR','Sweden');
insert into slotmachine.airline values('Servizi Aerei','SNM','Italy');
insert into slotmachine.airline values('Execujet Scandinavia','VMP','Denmark');
insert into slotmachine.airline values('Nordic Solutions','NVD','Lithuania');
insert into slotmachine.airline values('Royal Jet','ROJ','United Arab Emirates');
insert into slotmachine.airline values('Antonov Airlines','ADB','Ukraine');
insert into slotmachine.airline values('Swiss Air-Ambulance','SAZ','Switzerland');
insert into slotmachine.airline values('Jazeera Airways','JZR','Kuwait');
insert into slotmachine.airline values('AMC Airlines','AMV','Egypt');
insert into slotmachine.airline values('EuroAtlantic Airways','MMZ','Portugal');
insert into slotmachine.airline values('Polar Air Cargo','PAC','United States');
insert into slotmachine.airline values('Biman Bangladesh Airlines','BBC','Bangladesh');
insert into slotmachine.airline values('Slovak Government Flying Service','SSG','Slovakia');
insert into slotmachine.airline values('Si-Chang Flying Service','SCR','Thailand');
insert into slotmachine.airline values('ATRAN Cargo Airlines','VAS','Russian Federation');
insert into slotmachine.airline values('Star Air','SRR','Denmark');
insert into slotmachine.airline values('Abakan-Avia','ABG','Russia');
insert into slotmachine.airline values('TAAG Angola Airlines','DTA','Angola');
insert into slotmachine.airline values('CityJet','BCY','Ireland');
insert into slotmachine.airline values('Air Namibia','NMB','Namibia');
insert into slotmachine.airline values('Air Tahiti Nui','THT','France');
insert into slotmachine.airline values('Carga Express Internacional','EST','Mexico');
insert into slotmachine.airline values('Air Luxor GB','LXG','Guinea-Bissau');
insert into slotmachine.airline values('Air Madagascar','MDG','Madagascar');
insert into slotmachine.airline values('ACM Air Charter','BVR','Germany');
