insert into slotmachine.country values('Afghanistan');
insert into slotmachine.country values('Albania');
insert into slotmachine.country values('Algeria');
insert into slotmachine.country values('American Samoa');
insert into slotmachine.country values('Angola');
insert into slotmachine.country values('Anguilla');
insert into slotmachine.country values('Antarctica');
insert into slotmachine.country values('Antigua and Barbuda');
insert into slotmachine.country values('Argentina');
insert into slotmachine.country values('Armenia');
insert into slotmachine.country values('Aruba');
insert into slotmachine.country values('Australia');
insert into slotmachine.country values('Austria');
insert into slotmachine.country values('Azerbaijan');
insert into slotmachine.country values('Bahamas');
insert into slotmachine.country values('Bahrain');
insert into slotmachine.country values('Bangladesh');
insert into slotmachine.country values('Barbados');
insert into slotmachine.country values('Belarus');
insert into slotmachine.country values('Belgium');
insert into slotmachine.country values('Belize');
insert into slotmachine.country values('Benin');
insert into slotmachine.country values('Bermuda');
insert into slotmachine.country values('Bhutan');
insert into slotmachine.country values('Bolivia');
insert into slotmachine.country values('Bosnia and Herzegovina');
insert into slotmachine.country values('Botswana');
insert into slotmachine.country values('Brazil');
insert into slotmachine.country values('British Indian Ocean Territory');
insert into slotmachine.country values('British Virgin Islands');
insert into slotmachine.country values('Brunei');
insert into slotmachine.country values('Bulgaria');
insert into slotmachine.country values('Burkina Faso');
insert into slotmachine.country values('Burma');
insert into slotmachine.country values('Burundi');
insert into slotmachine.country values('Cambodia');
insert into slotmachine.country values('Cameroon');
insert into slotmachine.country values('Canada');
insert into slotmachine.country values('Cape Verde');
insert into slotmachine.country values('Cayman Islands');
insert into slotmachine.country values('Central African Republic');
insert into slotmachine.country values('Chad');
insert into slotmachine.country values('Chile');
insert into slotmachine.country values('China');
insert into slotmachine.country values('Christmas Island');
insert into slotmachine.country values('Cocos (Keeling) Islands');
insert into slotmachine.country values('Colombia');
insert into slotmachine.country values('Comoros');
insert into slotmachine.country values('Congo (Brazzaville)');
insert into slotmachine.country values('Congo (Kinshasa)');
insert into slotmachine.country values('Cook Islands');
insert into slotmachine.country values('Costa Rica');
insert into slotmachine.country values('Cote dIvoire');
insert into slotmachine.country values('Croatia');
insert into slotmachine.country values('Cuba');
insert into slotmachine.country values('Cyprus');
insert into slotmachine.country values('Czech Republic');
insert into slotmachine.country values('Denmark');
insert into slotmachine.country values('Djibouti');
insert into slotmachine.country values('Dominica');
insert into slotmachine.country values('Dominican Republic');
insert into slotmachine.country values('East Timor');
insert into slotmachine.country values('Ecuador');
insert into slotmachine.country values('Egypt');
insert into slotmachine.country values('El Salvador');
insert into slotmachine.country values('Equatorial Guinea');
insert into slotmachine.country values('Eritrea');
insert into slotmachine.country values('Estonia');
insert into slotmachine.country values('Ethiopia');
insert into slotmachine.country values('Falkland Islands');
insert into slotmachine.country values('Faroe Islands');
insert into slotmachine.country values('Fiji');
insert into slotmachine.country values('Finland');
insert into slotmachine.country values('France');
insert into slotmachine.country values('French Guiana');
insert into slotmachine.country values('French Polynesia');
insert into slotmachine.country values('Gabon');
insert into slotmachine.country values('Gambia');
insert into slotmachine.country values('Georgia');
insert into slotmachine.country values('Germany');
insert into slotmachine.country values('Ghana');
insert into slotmachine.country values('Gibraltar');
insert into slotmachine.country values('Greece');
insert into slotmachine.country values('Greenland');
insert into slotmachine.country values('Grenada');
insert into slotmachine.country values('Guadeloupe');
insert into slotmachine.country values('Guam');
insert into slotmachine.country values('Guatemala');
insert into slotmachine.country values('Guernsey');
insert into slotmachine.country values('Guinea');
insert into slotmachine.country values('Guinea-Bissau');
insert into slotmachine.country values('Guyana');
insert into slotmachine.country values('Haiti');
insert into slotmachine.country values('Honduras');
insert into slotmachine.country values('Hong Kong');
insert into slotmachine.country values('Hungary');
insert into slotmachine.country values('Iceland');
insert into slotmachine.country values('India');
insert into slotmachine.country values('Indonesia');
insert into slotmachine.country values('Iran');
insert into slotmachine.country values('Iraq');
insert into slotmachine.country values('Ireland');
insert into slotmachine.country values('Isle of Man');
insert into slotmachine.country values('Israel');
insert into slotmachine.country values('Italy');
insert into slotmachine.country values('Jamaica');
insert into slotmachine.country values('Japan');
insert into slotmachine.country values('Jersey');
insert into slotmachine.country values('Johnston Atoll');
insert into slotmachine.country values('Jordan');
insert into slotmachine.country values('Kazakhstan');
insert into slotmachine.country values('Kenya');
insert into slotmachine.country values('Kiribati');
insert into slotmachine.country values('Kuwait');
insert into slotmachine.country values('Kyrgyzstan');
insert into slotmachine.country values('Laos');
insert into slotmachine.country values('Latvia');
insert into slotmachine.country values('Lebanon');
insert into slotmachine.country values('Lesotho');
insert into slotmachine.country values('Liberia');
insert into slotmachine.country values('Libya');
insert into slotmachine.country values('Lithuania');
insert into slotmachine.country values('Luxembourg');
insert into slotmachine.country values('Macau');
insert into slotmachine.country values('Macedonia');
insert into slotmachine.country values('Madagascar');
insert into slotmachine.country values('Malawi');
insert into slotmachine.country values('Malaysia');
insert into slotmachine.country values('Maldives');
insert into slotmachine.country values('Mali');
insert into slotmachine.country values('Malta');
insert into slotmachine.country values('Marshall Islands');
insert into slotmachine.country values('Martinique');
insert into slotmachine.country values('Mauritania');
insert into slotmachine.country values('Mauritius');
insert into slotmachine.country values('Mayotte');
insert into slotmachine.country values('Mexico');
insert into slotmachine.country values('Micronesia');
insert into slotmachine.country values('Midway Islands');
insert into slotmachine.country values('Moldova');
insert into slotmachine.country values('Mongolia');
insert into slotmachine.country values('Montenegro');
insert into slotmachine.country values('Montserrat');
insert into slotmachine.country values('Morocco');
insert into slotmachine.country values('Mozambique');
insert into slotmachine.country values('Myanmar');
insert into slotmachine.country values('Namibia');
insert into slotmachine.country values('Nauru');
insert into slotmachine.country values('Nepal');
insert into slotmachine.country values('Netherlands');
insert into slotmachine.country values('Netherlands Antilles');
insert into slotmachine.country values('New Caledonia');
insert into slotmachine.country values('New Zealand');
insert into slotmachine.country values('Nicaragua');
insert into slotmachine.country values('Niger');
insert into slotmachine.country values('Nigeria');
insert into slotmachine.country values('Niue');
insert into slotmachine.country values('Norfolk Island');
insert into slotmachine.country values('North Korea');
insert into slotmachine.country values('Northern Mariana Islands');
insert into slotmachine.country values('Norway');
insert into slotmachine.country values('Oman');
insert into slotmachine.country values('Pakistan');
insert into slotmachine.country values('Palau');
insert into slotmachine.country values('Palestine');
insert into slotmachine.country values('Panama');
insert into slotmachine.country values('Papua New Guinea');
insert into slotmachine.country values('Paraguay');
insert into slotmachine.country values('Peru');
insert into slotmachine.country values('Philippines');
insert into slotmachine.country values('Poland');
insert into slotmachine.country values('Portugal');
insert into slotmachine.country values('Puerto Rico');
insert into slotmachine.country values('Qatar');
insert into slotmachine.country values('Reunion');
insert into slotmachine.country values('Romania');
insert into slotmachine.country values('Russia');
insert into slotmachine.country values('Rwanda');
insert into slotmachine.country values('Saint Helena');
insert into slotmachine.country values('Saint Kitts and Nevis');
insert into slotmachine.country values('Saint Lucia');
insert into slotmachine.country values('Saint Pierre and Miquelon');
insert into slotmachine.country values('Saint Vincent and the Grenadines');
insert into slotmachine.country values('Samoa');
insert into slotmachine.country values('Sao Tome and Principe');
insert into slotmachine.country values('Saudi Arabia');
insert into slotmachine.country values('Senegal');
insert into slotmachine.country values('Serbia');
insert into slotmachine.country values('Seychelles');
insert into slotmachine.country values('Sierra Leone');
insert into slotmachine.country values('Singapore');
insert into slotmachine.country values('Slovakia');
insert into slotmachine.country values('Slovenia');
insert into slotmachine.country values('Solomon Islands');
insert into slotmachine.country values('Somalia');
insert into slotmachine.country values('South Africa');
insert into slotmachine.country values('South Korea');
insert into slotmachine.country values('South Sudan');
insert into slotmachine.country values('Spain');
insert into slotmachine.country values('Sri Lanka');
insert into slotmachine.country values('Sudan');
insert into slotmachine.country values('Suriname');
insert into slotmachine.country values('Svalbard');
insert into slotmachine.country values('Swaziland');
insert into slotmachine.country values('Sweden');
insert into slotmachine.country values('Switzerland');
insert into slotmachine.country values('Syria');
insert into slotmachine.country values('Taiwan');
insert into slotmachine.country values('Tajikistan');
insert into slotmachine.country values('Tanzania');
insert into slotmachine.country values('Thailand');
insert into slotmachine.country values('Togo');
insert into slotmachine.country values('Tonga');
insert into slotmachine.country values('Trinidad and Tobago');
insert into slotmachine.country values('Tunisia');
insert into slotmachine.country values('Turkey');
insert into slotmachine.country values('Turkmenistan');
insert into slotmachine.country values('Turks and Caicos Islands');
insert into slotmachine.country values('Tuvalu');
insert into slotmachine.country values('Uganda');
insert into slotmachine.country values('Ukraine');
insert into slotmachine.country values('United Arab Emirates');
insert into slotmachine.country values('United Kingdom');
insert into slotmachine.country values('United States');
insert into slotmachine.country values('Uruguay');
insert into slotmachine.country values('Uzbekistan');
insert into slotmachine.country values('Vanuatu');
insert into slotmachine.country values('Venezuela');
insert into slotmachine.country values('Vietnam');
insert into slotmachine.country values('Virgin Islands');
insert into slotmachine.country values('Wake Island');
insert into slotmachine.country values('Wallis and Futuna');
insert into slotmachine.country values('West Bank');
insert into slotmachine.country values('Western Sahara');
insert into slotmachine.country values('Yemen');
insert into slotmachine.country values('Zambia');
insert into slotmachine.country values('Zimbabwe');
